In [ ]:
import numpy as np

# Question 1 :

In [10]:
A=np.array(["a","b","c","d"])
print(type(A))
print(type(A.tolist()))

<class 'numpy.ndarray'>
<class 'list'>


# Question 2 :

In [19]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print ("The sum of the diagonal of the matrice is equal to :",A.trace())

The sum of the diagonal of the matrice is equal to : 15


# Question 3 :

In [16]:
A = np.array([[1,2],[3,5]])
x = int(input('enter a number : '))
B = A[A>x]
print('the values higher than',x ,':',B)

enter a number : 2
the values higher than 2 : [3 5]


# Question 4 :

In [17]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])
C = a+b
print(C)

[ 2  4  6  8 10 12 14 16 18]


# Question 5 :

In [18]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (a.mean(axis=1, keepdims=True))
X = a-a.mean(axis=1, keepdims=True)
print (X)

[[2.]
 [5.]
 [8.]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
